spring.application.name=mvc-project
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret=wbEcdNrmS1HslKiWpVotft5YB3IVVJOrCz0RmQeHQMkd/rq6pNjPAYbbkrQH2C6Gv1E1nYLD3SYv3A/uXZJCzE251mH3cAM/tznmzKE9xKObWjljSCHLxc6y83Xeh0VWQtA36fFO0aqIAldrVFTtrz7XMa9ZqTCnJrNNMn20HfDi0eMIKZx/QmjG1f7pJEgBl8I7sVfrIES1HJaB0BEMeQ1y0zMBAeI47phSCU6kqiy2b2tU8s98SrJNJkhl6w5EqTdMltVsbPZFCSXfPb2FYMCahprnXJbyK3dTFoRuY6AZfi8hDjv2ZFRK8/8HNWEhSgipkutmgfsQt/EGE8fF
jwt.expiration=86400000